-- Migration SQL (phpMyAdmin/OVH) - Version20260413120000
-- Create fournisseur table (same business structure as clients)

CREATE TABLE IF NOT EXISTS `fournisseur` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `dossier_id` INT NOT NULL,
  `ville_id` INT DEFAULT NULL,
  `pays_id` INT DEFAULT NULL,
  `tarif_id` INT DEFAULT NULL,
  `reglement_id` INT DEFAULT NULL,
  `created_by_id` INT DEFAULT NULL,
  `modifed_by_id` INT DEFAULT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `adr1` VARCHAR(255) NOT NULL,
  `adr2` VARCHAR(255) DEFAULT NULL,
  `rue` VARCHAR(255) NOT NULL,
  `codepostal` INT DEFAULT NULL,
  `tel` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `web` VARCHAR(255) DEFAULT NULL,
  `linkedin` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_FOURNISSEUR_DOSSIER` (`dossier_id`),
  KEY `IDX_FOURNISSEUR_NOM` (`nom`),
  KEY `IDX_FOURNISSEUR_VILLE` (`ville_id`),
  KEY `IDX_FOURNISSEUR_PAYS` (`pays_id`),
  KEY `IDX_FOURNISSEUR_TARIF` (`tarif_id`),
  KEY `IDX_FOURNISSEUR_REGLEMENT` (`reglement_id`),
  KEY `IDX_FOURNISSEUR_CREATED_BY` (`created_by_id`),
  KEY `IDX_FOURNISSEUR_MODIFED_BY` (`modifed_by_id`),
  CONSTRAINT `FK_FOURNISSEUR_DOSSIER` FOREIGN KEY (`dossier_id`) REFERENCES `dossier` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_VILLE` FOREIGN KEY (`ville_id`) REFERENCES `ville` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_PAYS` FOREIGN KEY (`pays_id`) REFERENCES `pays` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_TARIF` FOREIGN KEY (`tarif_id`) REFERENCES `tarifs` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_REGLEMENT` FOREIGN KEY (`reglement_id`) REFERENCES `reglement` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_CREATED_BY` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_FOURNISSEUR_MODIFED_BY` FOREIGN KEY (`modifed_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
